## Put comments here that give an overall description of what your
## functions do
## Certain computations involving matices are simpler if the matrix is inverted. 
## This is a time consuming / costly process.
## In order to avoid repeated costly computations, the inverted matrix is stored in the cache.
## Later computations can access the cache without having to re-invert the matrix.  

## Write a short comment describing this function
## This function generates a matrix for further downstream computations. 

## example:
##  m <- makeCacheMatrix(matrix(1:4, 2,2))
##  cacheSolve(m)
##  cacheSolve(m) ### this call gets the message: getting cached data 

makeCacheMatrix <- function(x = matrix()) { 
    m <- NULL
    set <- function(y) {
        x <<- y
        m <<- NULL
    }
    get <- function() x # get returns x 
    setinverse <- function(mat) m <<- mat
    getinverse <- function() m
    list(set = set, get = get,
         setinverse = setinverse,
         getinverse = getinverse)
}
    



## Write a short comment describing this function
## This function calculates the inverse of a matrix generated by makeCacheMatrix above. 
## It first checks to see if the inverse of the matrix has already been calculated.
## If not, it then calculates it and saves it to the cache. 

cacheSolve <- function(x, ...) {
    m <- x$getinverse()      ## Return a matrix that is the inverse of 'x'
    if(!is.null(m)) {
        message("getting cached data")
        return(m)
    }
    data <- x$get()
    m <- solve(data)
    x$setinverse(m)
    m
}



